# **Creating New Features from Existing Data**

# 1. Load Dataset

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
# load dataset - telecom churn dataset
df = pd.read_csv("../datasets/telecom_churn.csv")
# display dataset
df.head()

,customer_id,signup_date,age,gender,city,education_level,employment_status,monthly_income,monthly_bill,internet_usage_gb,call_minutes,contract_type,support_tickets,customer_feedback,churn
0,10001,2019-01-01,65,Male,Multan,Bachelor,Employed,57643.0,10049.0,5.8,52.0,6-Month,1,Coverage is poor in my location,0
1,10002,2019-01-02,22,Female,Peshawar,Master,Employed,18207.0,2752.0,11.9,22.0,6-Month,2,Billing issues occurred multiple times,0
2,10003,2019-01-03,43,Male,Gujranwala,Secondary,Employed,13075.0,3155.0,40.0,87.0,Monthly,0,Billing issues occurred multiple times,0
3,10004,2019-01-04,21,Male,Lahore,Secondary,Employed,38890.0,5859.0,8.5,147.0,6-Month,2,Customer support was helpful,0
4,10005,2019-01-05,37,Female,Hyderabad,Primary,Employed,17475.0,5106.0,3.3,183.0,12-Month,0,Coverage is poor in my location,0

# 2. Extract Data Part - signup_data col

In [5]:
# convert date column to datetime format
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [11]:
# extract year, month, and day from signup_date column
df["signup_year"] = df["signup_date"].dt.year
df["signup_month"] = df["signup_date"].dt.month
df["signup_day"] = df["signup_date"].dt.dayofweek

# show new features
df[["signup_year", "signup_month", "signup_day"]].head()

   signup_year  signup_month  signup_day
0         2019             1           1
1         2019             1           2
2         2019             1           3
3         2019             1           4
4         2019             1           5

# 3. Ratio Feature Creation

In [15]:
# bill_income ratio
df["bill_income_ratio"] = df["monthly_bill"] / df["monthly_income"]

# show new feature
df[["monthly_bill", "monthly_income", "bill_income_ratio"]].head() 

# higher ratio, higher financial stress, higher churn risk

   monthly_bill  monthly_income  bill_income_ratio
0       10049.0         57643.0           0.174332
1        2752.0         18207.0           0.151151
2        3155.0         13075.0           0.241300
3        5859.0         38890.0           0.150656
4        5106.0         17475.0           0.292189

# 4. Interaction Features

In [19]:
# Interaction features are created by combining two or more existing features
# higher interaction value, higher churn risk
df ["support_bill_interaction"] = df["support_tickets"] * df["monthly_bill"]

# show new feature
df[["support_tickets", "monthly_bill", "support_bill_interaction"]].head()

   support_tickets  monthly_bill  support_bill_interaction
0                1       10049.0                   10049.0
1                2        2752.0                    5504.0
2                0        3155.0                       0.0
3                2        5859.0                   11718.0
4                0        5106.0                       0.0

# 5. Text Length Feature

In [22]:
# text length features
# longer feedback-more detailed feedback-more likely to churn
df["feedback_length"] = df["customer_feedback"].str.len()

# show new feature
df[["customer_feedback", "feedback_length"]].head()

                        customer_feedback  feedback_length
0         Coverage is poor in my location               31
1  Billing issues occurred multiple times               38
2  Billing issues occurred multiple times               38
3            Customer support was helpful               28
4         Coverage is poor in my location               31

# 6. Keyward Flag Features

In [27]:
# binary flag makes text ML friendly
df["complaint_flag"] = df["customer_feedback"].str.contains("slow|bad|poor|expensive|unreliable|problem|issue|drops",
                                                            case = False).astype(int)

# show new feature
df[["customer_feedback", "complaint_flag"]].head()

                        customer_feedback  complaint_flag
0         Coverage is poor in my location               1
1  Billing issues occurred multiple times               1
2  Billing issues occurred multiple times               1
3            Customer support was helpful               0
4         Coverage is poor in my location               1

# 7. Final Features Review

In [28]:
# display all new features
df[["signup_year", "signup_month", "signup_day", "bill_income_ratio", "support_bill_interaction", "feedback_length", "complaint_flag"]].head()

,signup_year,signup_month,signup_day,bill_income_ratio,support_bill_interaction,feedback_length,complaint_flag
0,2019,1,1,0.174332,10049.0,31,1
1,2019,1,2,0.151151,5504.0,38,1
2,2019,1,3,0.241300,0.0,38,1
3,2019,1,4,0.150656,11718.0,28,0
4,2019,1,5,0.292189,0.0,31,1