# **Creating New Features from Existing Data**

# 1. Load Dataset

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
# load dataset - telecom churn dataset
df = pd.read_csv("../datasets/telecom_churn.csv")
# display dataset
df.head()

,customer_id,signup_date,age,gender,city,education_level,employment_status,monthly_income,monthly_bill,internet_usage_gb,call_minutes,contract_type,support_tickets,customer_feedback,churn
0,10001,2019-01-01,65,Male,Multan,Bachelor,Employed,57643.0,10049.0,5.8,52.0,6-Month,1,Coverage is poor in my location,0
1,10002,2019-01-02,22,Female,Peshawar,Master,Employed,18207.0,2752.0,11.9,22.0,6-Month,2,Billing issues occurred multiple times,0
2,10003,2019-01-03,43,Male,Gujranwala,Secondary,Employed,13075.0,3155.0,40.0,87.0,Monthly,0,Billing issues occurred multiple times,0
3,10004,2019-01-04,21,Male,Lahore,Secondary,Employed,38890.0,5859.0,8.5,147.0,6-Month,2,Customer support was helpful,0
4,10005,2019-01-05,37,Female,Hyderabad,Primary,Employed,17475.0,5106.0,3.3,183.0,12-Month,0,Coverage is poor in my location,0

# 2. Extract Data Part - signup_data col

In [5]:
# convert date column to datetime format
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [11]:
# extract year, month, and day from signup_date column
df["signup_year"] = df["signup_date"].dt.year
df["signup_month"] = df["signup_date"].dt.month
df["signup_day"] = df["signup_date"].dt.dayofweek

# show new features
df[["signup_year", "signup_month", "signup_day"]].head()

   signup_year  signup_month  signup_day
0         2019             1           1
1         2019             1           2
2         2019             1           3
3         2019             1           4
4         2019             1           5

In [6]:
df.dtypes

customer_id                   int64
signup_date          datetime64[us]
age                           int64
gender                          str
city                            str
education_level                 str
employment_status               str
monthly_income              float64
monthly_bill                float64
internet_usage_gb           float64
call_minutes                float64
contract_type                   str
support_tickets               int64
customer_feedback               str
churn                         int64
dtype: object